### ISSUE TITLE
Add Features | CPU, Ram, Disque space and network activity

### ISSUE THREAD

**Issue by thomasbonsirven** [BlueSquare23/web-lgsm#11]
Hello,

I think that highlighting the resources of a game server as on the global server would be interesting.

Example: in the list of installed servers, the possibility of seeing graphs on CPU load, RAM, disk space and incoming and outgoing network activity, from the VM or physical server, or from the LXC.

Here an example command for one server (PalWorld)
`lgsm@weblgsm:~/web-lgsm$ pidstat -u -r -d -p $(pidof -s "PalServer-Linux-Test") 1`
The 1 at the end of the command refreshes the data every second.

The Output :
`12:39:19      UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
12:39:19     1000     12884   15.27    1.31    0.00    0.12   16.58     3  PalServer-Linux

12:39:19      UID       PID  minflt/s  majflt/s     VSZ     RSS   %MEM  Command
12:39:19     1000     12884    147.07      0.00 4639764 1225908  14.61  PalServer-Linux

12:39:19      UID       PID   kB_rd/s   kB_wr/s kB_ccwr/s iodelay  Command
12:39:19     1000     12884      0.14      4.97      0.00       0  PalServer-Linux`

This command is not ideal, at least not in its current format. But the idea is to do something like this: 
<img width="928" alt="image" src="https://github.com/BlueSquare23/web-lgsm/assets/18753454/a377933d-ddaf-4afa-b5ef-063edc99fdd6">
 And this is good too : 
 
<img width="230" alt="image" src="https://github.com/BlueSquare23/web-lgsm/assets/18753454/8e5a7289-247f-4883-8281-b78a7e7222d4">

This image provide to Pterodactyl Panel.

Do you think this is feasible?

**Comment by BlueSquare23** [comment]
Yeah that's not a bad idea. Thanks for pointing me to that Pterodactyl Panel. I have not seen that project before but it looks interesting. Definitely a lot more advanced then this little web app here. But yeah still cool to see what they have to offer.

The one thing about this project that I do want to kind of avoid is feature creep toward a general linux web gui. I think there are lots of tools out there already that do that sort of thing.

That being said, yeah I do kinda like the idea of some more general real time basic usage stats maybe even some graphs. I'll have to do some research see what I can figure out. I'll leave this issue open and add it to the ideas section of my Todo's!

**Comment by BlueSquare23** [comment]
Proud to announce this now exists and has been included in the new [v1.6 release](https://github.com/BlueSquare23/web-lgsm/releases/tag/v1.6)!

With realtime stats for:
* Disk Usage
* CPU % Usage
* CPU Load Avgs
* Mem % Usage
* Network IO (bytes in/out per sec)

![homepage](https://github.com/BlueSquare23/web-lgsm/assets/48586248/856766a9-6d83-4243-8cd3-56a84631e6c8)
