### ISSUE TITLE
Installation Works, but Setup Loops

### ISSUE THREAD

**Issue by dctheee** [BlueSquare23/web-lgsm#2]
Installed the webgui, but the interface has issues and it looks whenever I attempt to create a user:

![image](https://github.com/BlueSquare23/web-lgsm/assets/46223006/055ee705-ade9-49b4-89c6-d436d3a2258f)

Ubuntu 22.04 LTS, all dependencies installed. What am I missing here?

**Comment by BlueSquare23** [comment]
Hrrrm interesting... That's definitely not right. None of the Bootstrap CSS is showing, but off the top I'm not sure why. For reference that page is supposed to look like this.

https://github.com/BlueSquare23/web-lgsm/blob/master/docs/images/add_user.png

Unfortunately, I'm not able to reproduce this with a fresh install on a test Ubuntu 22.04 system.

As for helping you debug; I'd advise trying the following.

* What does the contents of your `web-lgsm.log` file look like? Any errors in there?
* You can try to start the server via the debug start script. You'll have to first source the python virtual env and then you can run the debug script to start the server in your terminal.
  - cd web-lgsm
  - source venv/bin/activate
  - python app.py
  - Go to, http://localhost:5000
  - Does that look any different, show any obvious errors?

**Comment by dctheee** [comment]
Thanks for your quick response!

Here's what I get when I source: 

![image](https://github.com/BlueSquare23/web-lgsm/assets/46223006/d169b62c-f36b-44a1-9b88-4de633f280b0)

I don't see any errors or anything when I look in the log. I'm at a loss as well.

**Comment by BlueSquare23** [comment]
So that output looks pretty normal. Did you click submit on the web page while running the server in your terminal like that? The server should have caught a POST request and I was hoping that would maybe have an error in it.

What about in your browser? If you hit F12 and go to the `network` tab, do you get any errors there when you try to click submit?

**Comment by dctheee** [comment]
> What about in your browser? If you hit F12 and go to the `network` tab, do you get any errors there when you try to click submit?

Ah! Looks like an issue with a CORS request:

![image](https://github.com/BlueSquare23/web-lgsm/assets/46223006/4df4d859-631d-4273-ae94-4f5728fc4c7a)

Is it expecting it to be secure? Appreciate the time you're spending to assist!

**Comment by BlueSquare23** [comment]
Hey, sorry took me so long to reply. Those CORS errors probably explain why your CSS is broken. And they might* be related. But that's actually not what I was talking about.

I meant spin up the server in your terminal in debug mode. Then in your browser go to `http://127.0.0.1:5000`, hit F12 to open the browser console, __then go to the network tab__. Finally, try to create a user and click submit.

#### So you can see here the before I click __Submit__:
![image](https://github.com/BlueSquare23/web-lgsm/assets/48586248/76d96ba1-a562-4d06-b324-9285d2658e58)

#### And then after:
![image](https://github.com/BlueSquare23/web-lgsm/assets/48586248/6228c408-5f45-43f3-af76-0d23cc9d7523)

After hitting submit you can see there in the browser's network tab, the first thing listed is a __POST__ to /setup with status 302 which you can also see reflected down in the terminal console: `"POST /setup HTTP/1.1" 302`.

Now yours doesn't do that, from what it sounds like. But if you can show me how exactly yours is failing, I might* be able to help you get it working. Also if you can provide me with some more information about what browser you're using that could be helpful too.

Long shot, but do you have JavaScript disabled by any chance?

**Comment by BlueSquare23** [comment]
> Is it expecting it to be secure? Appreciate the time you're spending to assist!

This app should work fine __without__ SSL (aka with just plain old http). You can see there from my previous screenshots `http://127.0.0.1:5000` renders fine. I've tested this in Firefox and Chrome.

You don't need SSL if you're just going to run this on your desktop and connect to in from a browser on that same system. But SSL _IS_ recommended for any sort of "production" deployment (aka if you're going to connect to it over the internet you don't want to send login creds in plain text).

**Comment by dctheee** [comment]
So, I think I might be an idiot. Reinstalled, did everything same as before, just through Linux server CLI. Did install just fine, changed init.sh to use 0.0.0.0, opened the firewall to port 12357 for a certain LAN machine, and boom, everything's happy.

Appreciate the help. Clearly just a ID10T error on my part.

**Comment by dctheee** [comment]
Considered closed!

**Comment by BlueSquare23** [comment]
Yeah no problem! Glad you figured it out. Hope you enjoy / get some use out of the project! If you ever need anything else feel free to reach out!

https://johnlradford.io/contact.php
