### ISSUE TITLE
error: externally-managed-environment

### ISSUE THREAD

**Issue by Funes727** [BlueSquare23/web-lgsm#23]
When I try to install web-lgsm I get this error:

####### Upgrading `pip3`...
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

I'm on fresh install of Ubuntu server 24.04.1 LTS

**Comment by BlueSquare23** [comment]
Ahh yeah good catch that's definitely broken! For now I'd say just comment that line out of the install.sh script and run it again, should work. Really pip needs updated after the venv is setup. Yeah that's my bad. Will fix soon, but yeah for now just comment out lines [#L66-L69](https://github.com/BlueSquare23/web-lgsm/blob/master/install.sh#L66-L69) from the install.sh script.

Thanks for pointing this out. Working on the new 1.8.0 release now, will fix this for that, and I'll also go head and patch 1.7.0 here soon!

**Comment by BlueSquare23** [comment]
Okay actually this was just a couple of lines change. So I just went ahead and fixed it now. Just put out a [new minor release v1.7.1](https://github.com/BlueSquare23/web-lgsm/releases/tag/v1.7.1) with this fix in it! If you go ahead and run git pull or reclone the repo you should be good now. Thanks for reporting this! Let me know if you run into any other issues!

**Comment by Funes727** [comment]
After updating the repo everything is working. Great work, thank You for this.
