### ISSUE TITLE
Problem when install ArkServer

### ISSUE THREAD

**Issue by Rwis6** [BlueSquare23/web-lgsm#25]
Hi

I've test to install Ark Survivol server with web-lgsm and it doesnt work, I've this error in the prompt

"UpdateUI: skip show logodlmopen steamconsole.so failed: steamconsole.so: cannot open shared object file: No such file or directory
[----] !!! Fatal Error: Failed to load steamconsole.so"

But if i launch the installation of arkserver in the folder just created "ARK:_Survival_Evolved" with "./arkserver install", It's fully work

I've test with the server of CS GO and I've no problem

Maybe the script of lgsm is not compatible with web-lgsm ?

Kindly

**Comment by Rwis6** [comment]
Hi,

I think I found the problem, it's the colon ":" in the name of the folder, it's a problem on lgsm

Sorry for the incoveniance

**Comment by BlueSquare23** [comment]
Sorry for not getting back to you sooner! Yeah that colon in the name is almost certainly the problem. I actually already fixed this in the code for the next release (v1.8 not out yet). I'll go ahead and try to get a patch out for for 1.7 as well to fix this and will close the issue when that's done.

Thanks for reporting! Once again sorry for not getting back to you sooner, irl work has been crazy.

**Comment by BlueSquare23** [comment]
Okay just went ahead and put out a patch / new minor release (v1.7.2) that fixes this!

https://github.com/BlueSquare23/web-lgsm/releases/tag/v1.7.2

Thanks again for reporting this. Sorry for not getting back to you sooner. Stay tuned for new major release v1.8.0 coming out soon! Probably another month or two, circa holidays, when I have a bit more time off from work to really get things wrapped up nicely.
