### ISSUE TITLE
Enable console commands

### ISSUE THREAD

**Issue by hobsRKM** [BlueSquare23/web-lgsm#9]

**Comment by BlueSquare23** [comment]
Hrrm yeah that's a good idea. I had thought about this a while ago, but kinda forgot about it. Thanks for bringing it back to my attention!

I'm going to close this as an issue and I've turned it into a Todo.

https://github.com/BlueSquare23/web-lgsm/blob/92237c8909104c42ed8bbe324873dff6957dea49/Todos.txt#L3

I'll figure out some sort of way to add the `send` button onto the controls page!

```send          sd   | Send command to game server console.
```

**Comment by BlueSquare23** [comment]
Included in version 1.5. Must be enabled by manually editing the `main.conf` file and changing `send_cmd` to equal yes.
